prod/: cleaned up atben clock frequency test
- prod/Common (begin), prod/atben: added clock reference file argument
- prod/atben (xtal_ben): use atrf-xtal options -b and -p to determine
  whether the clock frequency is correct

diff --git a/prod/Common b/prod/Common
--- a/prod/Common
+++ b/prod/Common
@@ -114,13 +114,20 @@ expect_re()
 begin()
 {
 	if [ -z "$1" ]; then
-		echo "usage: begin profile" 1>&2
+		echo "usage: begin profile [clock-ref]" 1>&2
 		exit 1
 	fi
 	PROFILE=$1
 	if [ ! -r $PROFILE ]; then
 		echo "$PROFILE not found" 1>&2
 		exit 1
+	fi
+	if [ "$2" ]; then
+		CLKREF=$2
+		if ! $LOCAL_EXEC "[ -r $CLKREF ]"; then
+			echo "$CLKREF not found" 1>&2
+			exit 1
+		fi
 	fi
 }
 
