atusb-flash: show avrdude progress output
- Common (doit): if the environment variable LIVE is set to "true",
  run the command in "script" instead of using "eval"
- Common (LIVE): unset this variable on initialization
- atusb-flash (flash): set LIVE, to obtain progress output from avrdude

diff --git a/prod/Common b/prod/Common
--- a/prod/Common
+++ b/prod/Common
@@ -18,6 +18,8 @@ DUT=$2
 LOG=_log
 >$LOG
 
+LIVE=
+
 if [ ${REF#net:} = $REF ]; then
 	REF_EXEC=
 else
@@ -100,7 +102,14 @@ cmd()
 
 _doit()
 {
-	eval "$cmd" >_out 2>&1 || { echo "exit code $?" | fail; exit 1; }
+	if ${LIVE:-false}; then
+		echo
+		script -c "$cmd" -q _out ||
+		    { echo "exit code $?" | fail; exit 1; }
+	else
+		eval "$cmd" >_out 2>&1 ||
+		    { echo "exit code $?" | fail; exit 1; }
+	fi
 }
 
 
