usrp: update filtering and display for uncorrupted measurement setup
We now have a much wider dynamic range of the signal (with better SNR).
The outliers are mainly WLAN interferences.

- usrp/evscan: changed threshold from -50 dB to -70 dB
- usrp/evscan: increase outlier tolerance from 2 dB to 10 dB
- usrp/plscan: changed display range from [-35:-25] to [-40:-5]

diff --git a/usrp/evscan b/usrp/evscan
--- a/usrp/evscan
+++ b/usrp/evscan
@@ -18,6 +18,6 @@ done
 for f in "$1"/24*; do
     echo -n `basename "$f"` ''
     for n in "$f"/data*; do
-	./fft $opts -s 100 0 20 50 <"$n" || echo "fft failed for $n" 1>&1
-    done | ./range -v 2
+	./fft $opts -s 100 0 20 70 <"$n" || echo "fft failed for $n" 1>&1
+    done | ./range -v 10
 done
